### PR TITLE
Cleanup step1

### PR DESCRIPTION
**Pull request by malec1984**
Hi!
I would like to contribute to your project.
For beginning I would like to clean all the warnings and then try to use enums or defines to get rid of the "magical" numbers.
I have added a sub menu for version, I think it would be nice to have a fw version, currently I just put there the CRC, but want to discuss with you how you want to have it, as git commit id or just a static number incremented.

### CODE REVIEW

**Comment by sparkybg** [comment]
Static number incremented should be better.

**Comment by sparkybg** [comment]
But I don't see where this added menu is.

**Comment by sparkybg** [comment]
...and, some things worked, some things didn't:

- I had to bring back "include "..\" - this didn't worked.
- I had to bring back "const void *"on OLEDWrite - this caused compile warnings.

I published a new version with these things done.

**Comment by malec1984** [comment]
Hi,
   
   - I had to bring back "const void *"on OLEDWrite - this caused compile warnings.
If you refer to this: mcuSPISendBytes((int*)OLEDBUFF.B[r], 128 );
 mcuSPISendBytes((unsigned int*)OLEDBUFF.B[r], 128 );
it's a bit strange, I don't get warning, but I guess you refer to something else. The arguments type of OLEDWrite I haven't actually touched, as I haven't yet removed all the warnings :)I'm actually using linux environment and on linux include local folder is "./" and I thought on Windows it would work with ".\" but didn't test it, sorry for that.
Please feel free to add comments on the pull request before merging, I can as well introduce problems, I try not to :)    On Tuesday, January 5, 2021, 07:09:32 PM GMT+1, Spartak Timchev <notifications@github.com> wrote:  
 
 


...and, some things worked, some things didn't:
   
   - I had to bring back "include ".." - this didn't worked.
   - I had to bring back "const void *"on OLEDWrite - this caused compile warnings.

I published a new version with these things done.

**Comment by sparkybg** [comment]
There are no warnings when I compile. And there was not warnings before your pull request. Maybe it is something windows/linux related - i don;t know. I compile it under Windows MPLAB X. Never had Linux on my machine.

Anyway, the other things worked, so it was not a big deal to bring back the things that didn't. Check if you are using the same compiler version - I am using XC32 v2.50 at the moment.

**Comment by malec1984** [comment]
You don't get any warning because all warnings are disabled.To enable the warnings in compiler option set the additional-warningsThis will add -Wall as compile flag. I think there are a bit more than 50 warnings left after my changes. (more than 100 before)
I am using as well XC32 v2.50 as I have installed it just a few days ago.    On Tuesday, January 5, 2021, 07:50:52 PM GMT+1, Spartak Timchev <notifications@github.com> wrote:  
 
 


There are no warnings when I compile. And there was not warnings before your pull request. Maybe it is something windows/linux related - i don;t know. I compile it under Windows MPLAB X. Never had Linux on my machine.

Anyway, the other things worked, so it was not a big deal to bring back the things that didn't. Check if you are using the same compiler version - I am using XC32 v2.50 at the moment.

**Comment by sparkybg** [comment]
Warnings are there, but only "serious" warnings. :)

Anyway - check it out now everything is clean now.

Only "missing braces on initialization" warning is disabled now.

I was also a bit on the edge about "pointer arithmetic" warnings, but decided to resolve them.

**Comment by malec1984** [comment]
Hi, From the mail time I see you stayed late.. This shows me that you are dedicated for this project :)
Great, you fixed all the warnings :)
I managed to make a Windows setup and I can see that on windows the compiler doesn't know how to interpret the -I".\" so MPLAB is actually converting the .\ to ./ but this works for linux as windows uses backslash and not slash, so I'll have to see if there is other way.
Just a matter of taste for programming I guess, I've see you are using this:if( a=b ) then...I personally do first the assignment and then the check as it would be more clear on reading the flow.ex  a=b; if(a) then..
I would like to add also comments on the functions, just because if you look at it in a few years I'm pretty sure you will also need a bit of time to remember what you wanted to do :), this I'm talking from my own experience.
So on my next pull request I will add comments on it so if my understanding is wrong in some places you can add comments and then I will do another commit to solve them.
Cheers,Radu.
    On Wednesday, January 6, 2021, 01:10:40 AM GMT+1, Spartak Timchev <notifications@github.com> wrote:  
 
 


Warnings are there, but only "serious" warnings. :)

Anyway - check it out now everything is clean now.

Only "missing braces on initialization" warning is disabled now.

I was also a bit on the edge about "pointer arithmetic" warnings, but decided to resolve them.

**Pull request merged**
